image: devwithlando/gitpod:1


tasks:
 - name: Setup Drupal Dev Env
   init: |
     docker build -t devwithlando/php:8.0-apache-4 .
     docker build -t devwithlando/phpmyadmin:5.1.1 .
   command: |
     lando start
     lando composer require drush/drush
     lando composer install
     chmod ug+w -R /workspace/lando-drupal-gitpod/web/sites/default
     lando drush si -y --account-pass=admin --site-name='lando_drupal9' --db-url=mysql://drupal9:drupal9@database/drupal9 demo_umami



ports:
  - port: 3306
    onOpen: ignore
  - port: 80
    onOpen: ignore
  - port: 443
    onOpen: ignore

vscode:
  extensions:
    - felixfbecker.php-debug
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - EditorConfig.EditorConfig
    - esbenp.prettier-vscode
    - stylelint.vscode-stylelint
    - tombonnike.vscode-status-bar-format-toggle
    - usernamehw.errorlens
    - mblode.twig-language
    - skippednote.VS-code-drupal
