image: devwithlando/gitpod:1


tasks:
 - name: Setup Drupal Dev Env
   init: |
     docker build -t devwithlando/php:8.0-apache-4 .
     docker build -t devwithlando/phpmyadmin:5.1.1 .
   command: |
     lando start
     lando composer require drush/drush
     lando composer install
     lando composer require drush/config-extra
     chmod ug+w -R /workspace/lando-drupal-gitpod/web/sites/default
     lando drush si -y --account-pass=VcUx2LtiB6 --site-name='drupal_govt_policy' --db-url=mysql://dgp:drupgovtpol@database/drupal_govt_policy_db minimal


vscode:
  extensions:
    - felixfbecker.php-debug
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - EditorConfig.EditorConfig
    - esbenp.prettier-vscode
    - stylelint.vscode-stylelint
    - tombonnike.vscode-status-bar-format-toggle
    - usernamehw.errorlens
    - mblode.twig-language
    - skippednote.VS-code-drupal
