name: lando-drupal-gitpod
recipe: drupal9
config:
  webroot: web

services:
  myservice:
    type: phpmyadmin
    creds:
      user: mysql -> dgp
      password: mysql -> drupgovtpol
      database: database -> drupal_govt_policy
