name: lando-drupal-gitpod
recipe: drupal9
config:
 webroot: web
 
services:
 database:
   creds:
     database: drupal_govt_policy
     user: dgp
     password: drupgovtpol
 myservice:
   type: phpmyadmin
